(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const main=$('#mainContent'), drawer=$('#sidebar'), backdrop=$('#drawerBackdrop'), menu=$('#hamburgerBtn');
const groups=[
 ['Image Tools',/^(qr|idphoto|img|image|grayscale|sepia|brightness|rotateflip|crop|textimage)/i],
 ['Text & Writing',/^(text|char|case|word|line|remove|sort|slug|lorem|markdown|regex)/i],
 ['Crypto & Security',/^(hash|sha|md5|base64|uuid|password|jwt|encrypt|decrypt|hmac|crypto)/i],
 ['Developer & Web',/^(json|xml|html|css|js|javascript|sql|url|timestamp|color|http|useragent|regex|dev)/i],
 ['Math & Numbers',/^(calc|math|percent|fraction|average|random|number|prime|factor|ratio)/i],
 ['Converters',/^(convert|length|weight|mass|temp|speed|area|volume|data|time|unit|currency)/i],
 ['Date & Time',/^(date|time|age|timezone|countdown|days)/i],
 ['Finance',/^(loan|emi|interest|tip|tax|finance|discount|split)/i],
 ['Health & Body',/^(bmi|bmr|calorie|health|body|pregnancy)/i]
];
function toolEntries(){return typeof TOOLS==='object'&&TOOLS?Object.entries(TOOLS).filter(([,t])=>t&&typeof t.render==='function'):[]}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function openDrawer(){drawer.classList.add('open');backdrop.classList.add('open');menu.classList.add('open');menu.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'}
function closeDrawer(){drawer.classList.remove('open');backdrop.classList.remove('open');menu.classList.remove('open');menu.setAttribute('aria-expanded','false');document.body.style.overflow=''}
function buildDrawer(){const entries=toolEntries();let used=new Set();let html='';for(const [title,re] of groups){const list=entries.filter(([id])=>re.test(id));if(!list.length)continue;list.forEach(([id])=>used.add(id));html+=`<section class="drawer-section"><h3>${title}</h3><ul class="drawer-list">${list.map(([id,t])=>`<li><button data-tool="${esc(id)}">${esc(t.name||id)}</button></li>`).join('')}</ul></section>`}const rest=entries.filter(([id])=>!used.has(id));if(rest.length)html+=`<section class="drawer-section"><h3>More Tools</h3><ul class="drawer-list">${rest.map(([id,t])=>`<li><button data-tool="${esc(id)}">${esc(t.name||id)}</button></li>`).join('')}</ul></section>`;drawer.insertAdjacentHTML('beforeend',html)}
function landing(){main.innerHTML=`<section class="landing"><div class="hero"><div><span class="eyebrow">✦ 90+ TOOLS · FAST · PRIVATE</span><h1>One place.<br>Every tool.</h1><p>Transform images, PDFs, text, numbers, code and everyday data directly in your browser. No complicated setup. No clutter. Just tools that work.</p><div class="hero-actions"><button class="btn" id="heroBrowse">☰ Explore all tools</button><button class="btn ghost" id="heroPopular">✨ Try a popular tool</button></div></div><div class="hero-art"><div class="hero-glow"></div><div class="device"><div class="device-top"><i></i><i></i><i></i></div><div class="mock-search">⌕ &nbsp; Search 90+ tools…</div><div class="mock-grid"><div class="mock-card"><b>QR Generator</b><small>Instant</small></div><div class="mock-card"><b>Image → PDF</b><small>Private</small></div><div class="mock-card"><b>SHA-256</b><small>Secure</small></div></div></div></div></div><div class="feature-grid"><article class="feature">⚡<strong>Instant in-browser</strong><p>Tools respond directly in the page with no unnecessary round trips.</p></article><article class="feature">🔒<strong>Privacy focused</strong><p>Client-side tools process your files locally whenever the browser allows it.</p></article><article class="feature">📱<strong>Made for phones</strong><p>A touch-first interface with a drawer that keeps the homepage clean.</p></article></div><h2 class="section-title">Popular tools</h2><div class="tool-preview" id="popularTools"></div></section>`;
const entries=toolEntries().slice(0,8);$('#popularTools').innerHTML=entries.map(([id,t])=>`<button class="preview-card" data-tool="${esc(id)}"><span>✦ TOOL</span><b>${esc(t.name||id)}</b><span>${esc(t.desc||'Ready to use')}</span></button>`).join('');$('#heroBrowse').onclick=openDrawer;$('#heroPopular').onclick=()=>entries[0]&&route(entries[0][0]);}
function route(id){const t=TOOLS&&TOOLS[id];if(!t||typeof t.render!=='function')return;history.pushState({},'',`#/${encodeURIComponent(id)}`);closeDrawer();main.innerHTML=`<section class="tool-page"><div class="tool-head"><span class="eyebrow">TOOLBOX PRO</span><h1>${esc(t.name||id)}</h1><p>${esc(t.desc||'Browser tool')}</p></div><div class="tool-card" id="activeTool"></div></section><div class="ad-slot"><span>ADVERTISEMENT</span><strong>MoneyTag / Monetag space</strong></div>`;try{t.render($('#activeTool'))}catch(e){$('#activeTool').innerHTML=`<div class="result-box">This tool encountered an error while loading. Please reload and try again.</div>`;console.error('Tool render error',id,e)};$$('.drawer-list button').forEach(b=>b.classList.toggle('active',b.dataset.tool===id));window.scrollTo({top:0,behavior:'smooth'})}
function current(){const h=decodeURIComponent(location.hash.replace(/^#\/?/,''));return h||null}
function render(){const id=current();if(id&&TOOLS[id])route(id);else landing()}
menu.addEventListener('click',()=>drawer.classList.contains('open')?closeDrawer():openDrawer());$('#drawerClose').addEventListener('click',closeDrawer);backdrop.addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();$('#modalOverlay').classList.remove('open')}});drawer.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)route(b.dataset.tool)});main.addEventListener('click',e=>{const b=e.target.closest('[data-tool]');if(b)route(b.dataset.tool)});window.addEventListener('popstate',render);window.addEventListener('hashchange',render);
$('#toolSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){buildDrawer();return}const found=toolEntries().filter(([id,t])=>(id+' '+(t.name||'')+' '+(t.desc||'')).toLowerCase().includes(q)).slice(0,20);drawer.innerHTML=`<div class="drawer-head"><b>Search results</b><button id="drawerCloseSearch">×</button></div><section class="drawer-section"><ul class="drawer-list">${found.map(([id,t])=>`<li><button data-tool="${esc(id)}">${esc(t.name||id)}</button></li>`).join('')||'<li><button disabled>No matching tools</button></li>'}</ul></section>`;openDrawer()});
const cookie=$('#cookieBanner');const cookieKey='toolboxpro-cookie-choice';if(!localStorage.getItem(cookieKey))cookie.classList.add('show');$('#cookieAcceptBtn').onclick=()=>{localStorage.setItem(cookieKey,'accepted');cookie.classList.remove('show')};$('#cookieDeclineBtn').onclick=()=>{localStorage.setItem(cookieKey,'necessary');cookie.classList.remove('show')};
const modal=$('#modalOverlay'),box=$('#modalBox');$('#modalClose').onclick=()=>modal.classList.remove('open');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});document.addEventListener('click',e=>{const b=e.target.closest('[data-modal]');if(!b)return;const type=b.dataset.modal;const data={about:['About Toolbox Pro','Toolbox Pro is a collection of browser-first utilities designed to make everyday tasks quick and simple.'],privacy:['Privacy','Files are processed locally by tools that support client-side processing. Third-party advertising, when enabled, is governed by the relevant provider policies.'],contact:['Contact','For support, review the repository or add your preferred support address before publishing the site.']};const d=data[type]||data.about;box.innerHTML=`<h2>${d[0]}</h2><p>${d[1]}</p>`;modal.classList.add('open')});$('#yearNow').textContent=new Date().getFullYear();
requestAnimationFrame(()=>{buildDrawer();render()});
})();