/* Toolinger final site shell: one mobile drawer, landing-only home, consent, brand, motion background. */
(function(){
'use strict';
const BRAND='Toolinger';
function addStyle(){if(document.getElementById('toolinger-final-style'))return;const s=document.createElement('style');s.id='toolinger-final-style';s.textContent=`
:root{--ti-p:#6956ff;--ti-b:#22b8ff;--ti-t:#17213b}
body{background:#f7f9ff!important;color:var(--ti-t)!important}
.site-header{z-index:10010!important}
.brand-mark{overflow:hidden!important;padding:0!important;background:#11152b!important}.brand-mark img{width:100%;height:100%;object-fit:cover;display:block}.brand-text strong{color:#17213b!important}
.sidebar{z-index:10003!important;pointer-events:auto!important}#toolideaNavBackdrop{z-index:10002!important;pointer-events:none!important}#toolideaNavBackdrop.is-visible{pointer-events:auto!important}
#toolingerBackdrop{position:fixed;inset:0;background:rgba(18,25,55,.24);z-index:10002;display:none;opacity:0;touch-action:manipulation}#toolingerBackdrop.is-visible{display:block;opacity:1}
@media(max-width:900px){.hamburger{display:flex!important;align-items:center;justify-content:center!important;position:relative!important;z-index:10011!important;width:60px!important;height:54px!important;font-size:0!important;background:rgba(255,255,255,.96)!important;color:#26304f!important;border:1px solid rgba(80,70,160,.16)!important;border-radius:17px!important;touch-action:manipulation!important}.hamburger::before{content:'☰';font:34px/1 Arial,sans-serif}.hamburger[aria-expanded="true"]::before{content:'×';font-size:42px}#toolideaDrawer{z-index:10009!important;pointer-events:auto!important}}
.ti-home{position:relative;min-height:680px;overflow:hidden;border-radius:32px;padding:54px 34px 38px;background:rgba(255,255,255,.78);border:1px solid rgba(80,75,170,.14);box-shadow:0 28px 90px rgba(67,60,145,.14)}
.ti-motion{position:absolute;inset:0;overflow:hidden;pointer-events:none;background:linear-gradient(120deg,#eef4ff,#faf5ff,#effcff,#fff5fb);background-size:300% 300%;animation:tiVideo 14s ease-in-out infinite alternate}.ti-motion:before,.ti-motion:after{content:'';position:absolute;border-radius:50%;filter:blur(22px);opacity:.55;mix-blend-mode:multiply}.ti-motion:before{width:360px;height:360px;left:-90px;top:-70px;background:radial-gradient(circle,#7c5cff,transparent 68%);animation:tiFloat1 9s ease-in-out infinite}.ti-motion:after{width:420px;height:420px;right:-130px;bottom:-120px;background:radial-gradient(circle,#22b8ff,transparent 68%);animation:tiFloat2 11s ease-in-out infinite}
@keyframes tiVideo{0%{background-position:0% 50%;filter:hue-rotate(0deg)}50%{background-position:100% 30%;filter:hue-rotate(7deg)}100%{background-position:30% 100%;filter:hue-rotate(-6deg)}}@keyframes tiFloat1{50%{transform:translate(80px,110px) scale(1.15)}}@keyframes tiFloat2{50%{transform:translate(-100px,-80px) scale(1.12)}}
.ti-home-content{position:relative;z-index:2;max-width:720px}.ti-kicker{display:inline-flex;padding:8px 13px;border-radius:99px;background:rgba(105,86,255,.1);border:1px solid rgba(105,86,255,.14);color:#5846c5;font-weight:800;font-size:.74rem;letter-spacing:1.4px;text-transform:uppercase}.ti-home h1{font:700 clamp(3rem,8vw,6.8rem)/.9 'Space Grotesk',sans-serif;letter-spacing:-4px;margin:20px 0;color:#16213e}.ti-home h1 span{background:linear-gradient(90deg,#6956ff,#19bff0,#ff4ecd);-webkit-background-clip:text;background-clip:text;color:transparent}.ti-home p{max-width:670px;font-size:1.08rem;line-height:1.8;color:#64708a}.ti-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.ti-action{min-height:52px;padding:0 22px;border:0;border-radius:999px;background:linear-gradient(135deg,#6956ff,#22b8ff);color:#fff;font-weight:800;box-shadow:0 14px 32px rgba(91,76,215,.24);cursor:pointer}.ti-action.secondary{background:rgba(255,255,255,.9);color:#303b59;border:1px solid rgba(80,75,170,.14)}
.ti-cubes{position:absolute;right:5%;top:12%;width:390px;height:390px;z-index:2;transform:perspective(900px) rotateX(8deg) rotateY(-14deg);pointer-events:none}.ti-cube{position:absolute;width:92px;height:92px;border-radius:22px;background:linear-gradient(145deg,rgba(255,255,255,.94),rgba(220,231,255,.7));border:1px solid rgba(105,86,255,.18);box-shadow:0 25px 55px rgba(54,60,140,.18);display:grid;place-items:center;font-size:2.1rem;animation:tiCube 5s ease-in-out infinite}.ti-cube:nth-child(1){left:45px;top:25px}.ti-cube:nth-child(2){right:30px;top:120px;animation-delay:-1.2s}.ti-cube:nth-child(3){left:105px;bottom:35px;animation-delay:-2.2s}.ti-cube:nth-child(4){right:85px;bottom:0;animation-delay:-3.2s}@keyframes tiCube{50%{transform:translateY(-22px) rotate(6deg)}}
.ti-home-ad{position:relative;z-index:3;margin:26px 0}.ti-features{position:relative;z-index:3;display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:18px}.ti-feature{padding:18px;border-radius:20px;background:rgba(255,255,255,.74);border:1px solid rgba(80,75,170,.11);box-shadow:0 12px 32px rgba(65,60,140,.07)}.ti-feature b{display:block;margin-bottom:6px}.ti-feature span{font-size:.82rem;color:#6b7892;line-height:1.5}
.ti-consent{position:fixed;left:14px;right:14px;bottom:14px;z-index:20000;max-width:760px;margin:auto;padding:18px 20px;border-radius:22px;background:rgba(255,255,255,.97);border:1px solid rgba(80,75,170,.16);box-shadow:0 22px 70px rgba(27,32,70,.24);color:#26304f}.ti-consent h3{font-size:1rem;margin-bottom:6px}.ti-consent p{font-size:.78rem;line-height:1.55;color:#64708a}.ti-consent-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.ti-consent-actions button{border:0;border-radius:999px;padding:10px 15px;font-weight:800;cursor:pointer}.ti-consent-accept{background:linear-gradient(135deg,#6956ff,#22b8ff);color:#fff}.ti-consent-necessary,.ti-consent-more{background:#eef1fb;color:#33405d}
@media(max-width:900px){.ti-home{min-height:650px;padding:34px 20px 28px;border-radius:24px}.ti-home h1{letter-spacing:-2px}.ti-cubes{opacity:.34;right:-120px;top:18%;transform:scale(.72) perspective(900px) rotateX(8deg) rotateY(-14deg)}.ti-features{grid-template-columns:1fr}.ti-home p{font-size:.96rem}.ti-action{flex:1 1 190px}}
@media(prefers-reduced-motion:reduce){.ti-motion,.ti-motion:before,.ti-motion:after,.ti-cube{animation:none!important}}
`;document.head.appendChild(s)}
function logoMarkup(){return '<img src="./toolinger-logo.webp" alt="Toolinger logo" loading="eager">'}
function brand(){document.title='Toolinger – 90+ Free Online Tools';document.querySelectorAll('.brand-text strong,.footer-col strong').forEach(e=>e.textContent=BRAND);document.querySelectorAll('.brand-text span').forEach(e=>e.textContent='90+ ONLINE TOOLS');document.querySelectorAll('.brand').forEach(e=>{e.setAttribute('aria-label','Toolinger home');const m=e.querySelector('.brand-mark');if(m)m.innerHTML=logoMarkup()});if(window.TOOLIDEA_CONFIG){TOOLIDEA_CONFIG.brand=BRAND;TOOLIDEA_CONFIG.tagline='90+ Free Online Tools'}document.querySelectorAll('.footer-bottom').forEach(e=>e.innerHTML='<span>© '+new Date().getFullYear()+' Toolinger.</span><span>Browser-first processing where supported.</span>')}
function installConsent(){if(window.__toolingerConsentInstalled)return;window.__toolingerConsentInstalled=true;const old=document.getElementById('cookieBanner');if(old)old.remove();if(localStorage.getItem('toolinger-consent-v1'))return;const box=document.createElement('section');box.className='ti-consent';box.innerHTML='<h3>Privacy & cookie choices</h3><p>Toolinger uses local browser storage for preferences such as consent. No advertising network is enabled until a real Monetag configuration is added. You can choose necessary-only or allow advertising when it is enabled.</p><div class="ti-consent-actions"><button class="ti-consent-accept" data-c="all">Allow advertising</button><button class="ti-consent-necessary" data-c="necessary">Necessary only</button><button class="ti-consent-more" data-modal="privacy">Privacy policy</button></div>';document.body.appendChild(box);box.addEventListener('click',e=>{const b=e.target.closest('[data-c]');if(!b)return;localStorage.setItem('toolinger-consent-v1',b.dataset.c);box.remove()})}
function installNav(){if(window.__toolingerNavInstalled)return;const btn=document.getElementById('toolideaMenuBtn')||document.getElementById('hamburgerBtn'),drawer=document.getElementById('sidebar');if(!btn||!drawer)return;window.__toolingerNavInstalled=true;btn.id='toolideaMenuBtn';drawer.id='toolideaDrawer';let back=document.getElementById('toolingerBackdrop');if(!back){back=document.createElement('div');back.id='toolingerBackdrop';document.body.appendChild(back)}let open=false;const set=v=>{open=!!v;drawer.classList.toggle('is-open',open);back.classList.toggle('is-visible',open);btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Close tool categories':'Open tool categories');document.body.style.overflow=open&&innerWidth<=900?'hidden':''};btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();set(!open)},{capture:true,passive:false});back.addEventListener('click',()=>set(false));drawer.addEventListener('click',e=>{const li=e.target.closest('#sidebarContent li');if(li){const key=li.dataset.tool;if(key){e.preventDefault();location.hash='#/'+key}set(false)}});window.addEventListener('hashchange',()=>set(false));window.addEventListener('resize',()=>{if(innerWidth>900)set(false)},{passive:true});window.ToolingerNav={open:()=>set(true),close:()=>set(false)}}
function landing(){const tc=document.getElementById('toolContainer'),side=document.getElementById('sidebar'),title=document.getElementById('toolTitle'),desc=document.getElementById('toolDesc');if(!tc)return;const hash=location.hash.replace('#/','').trim();if(hash){if(side)side.classList.remove('ti-home-hide');return}if(side)side.classList.add('ti-home-hide');if(title)title.textContent='Toolinger';if(desc)desc.textContent='90+ online tools for everyday digital work';tc.innerHTML=`<section class="ti-home"><div class="ti-motion"></div><div class="ti-home-content"><span class="ti-kicker">90+ TOOLS · ONE SIMPLE WORKSPACE</span><h1>One place for <span>everything</span> you do online.</h1><p>Convert files, edit images, work with PDFs, calculate, generate, format and solve everyday digital tasks from one fast mobile-first toolbox. No account required for browser-first tools.</p><div class="ti-actions"><button class="ti-action" id="tiExplore">☰ Explore all tools</button><button class="ti-action secondary" data-modal="about">Learn about Toolinger</button></div></div><div class="ti-cubes" aria-hidden="true"><div class="ti-cube">🖼️</div><div class="ti-cube">📄</div><div class="ti-cube">🧮</div><div class="ti-cube">⚙️</div></div><div class="ad-slot ti-home-ad"><span class="ad-label">Advertisement</span><div class="ad-placeholder"><span>Ad space reserved</span></div></div><div class="ti-features"><div class="ti-feature"><b>⚡ Fast</b><span>Lightweight browser tools designed for quick results.</span></div><div class="ti-feature"><b>🔒 Private by design</b><span>Supported local tools process files directly in your browser.</span></div><div class="ti-feature"><b>📱 Mobile first</b><span>Touch-friendly layouts built for phones and tablets.</span></div></div></section>`;document.getElementById('tiExplore').onclick=()=>window.ToolingerNav?.open()}
function init(){addStyle();brand();installNav();landing();installConsent();document.querySelectorAll('.ad-placeholder').forEach(x=>x.setAttribute('aria-label','Advertisement'))}
window.addEventListener('hashchange',landing);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();setTimeout(init,700)
})();
