export const LEGAL_CONTENT: Record<string, { title: string; body: string }> = {
  about: {
    title: "About Toolinger",
    body: "Toolinger brings everyday image, PDF, text, developer and calculation tools together in your browser. No account is required. Tools are free to use.\n\nFile processing happens on your device. Optional AI features download models before running locally. Review important results before relying on them.",
  },
  privacy: {
    title: "Privacy policy",
    body: "Updated 8 October 2026\n\nFiles and text\nTool operations run in your browser. This build does not upload your inputs to a Toolinger server or keep an account database. Downloaded results stay on your device. Notepad and daily-life entries (tasks, habits, expenses, shopping, meals, packing and hydration) are saved in local browser storage until you clear them. There is no account sync or server backup. You may export a private backup file from My space.\n\nPreferences\nYour theme, favourite tools and recent tool IDs are stored locally. Recent history stores tool names, not input text or files. You can clear these preferences from Privacy choices.\n\nNetwork requests\nHosting providers receive normal request information, such as IP address and browser information. AI libraries and model files may be downloaded from Hugging Face, jsDelivr or unpkg. Those providers receive network request information under their own policies; your tool input is processed locally. The service worker caches app assets for repeat visits.\n\nAdvertising and analytics\nToolinger is prepared for Google AdSense. Ads remain disabled until valid publisher details and a certified consent platform are configured. When enabled, Google and its partners may use cookies, device identifiers, IP address, browser information and ad interactions for ad delivery, fraud prevention and measurement. Optional ad scripts load only after advertising permission and the required consent signal. No analytics integration is active. Google’s policies are available at https://policies.google.com/privacy and https://policies.google.com/technologies/ads.\n\nYour choices\nYou can delete local preferences, clear daily-life data in My space, clear your notepad, and remove cached app data using browser site settings. You may ask about applicable privacy rights, including access, correction, deletion and objection, at the contact address below. Toolinger cannot retrieve local browser entries from its servers. For privacy questions or requests contact lootchaser2026@gmail.com. Avoid sending sensitive files in support messages.",
  },
  terms: {
    title: "Terms of use",
    body: "Updated 8 October 2026\n\nUse Toolinger lawfully. You are responsible for the content you process and must have permission to use it. Do not use the tools to violate privacy, intellectual property rights or applicable law.\n\nThe tools are provided as available, without a guarantee of accuracy, uninterrupted access or suitability for a particular purpose. Keep original files and check exported results. To the extent permitted by applicable law, Toolinger is not liable for losses resulting from use of these utilities. Your statutory rights remain unaffected.\n\nThird-party libraries have their own licences and service terms. Features and these terms may change. Questions: lootchaser2026@gmail.com.",
  },
  cookies: {
    title: "Cookie & storage policy",
    body: "Updated 8 October 2026\n\nWhile ads are disabled, Toolinger does not set marketing cookies. It uses local storage for your theme, favourite and recent tools, optional notepad autosave, daily-life entries and a versioned advertising consent choice. If AdSense is enabled with permission, Google and its partners may use cookies and device identifiers for ads and measurement. A service worker stores app assets in the browser cache.\n\nUse Advertising privacy choices to refuse or allow optional ad storage, and Privacy choices to clear tool preferences. You can change an advertising choice at any time. Browser Global Privacy Control and Do Not Track signals block the advertising integration. Clear daily-life entries in My space. Clear notes inside Notepad. To remove all cached content, use your browser’s site-data controls. Storage restrictions do not prevent core tools from running, but preferences may not persist.",
  },
  disclaimer: {
    title: "Disclaimer",
    body: "Health, financial and other calculations are estimates for general information, not medical, financial, tax or legal advice. Consult a qualified professional for consequential decisions.\n\nPassport and ID photo sizes are templates. Toolinger does not check official compliance or guarantee acceptance. Verify the issuing authority’s current dimensions, head-size, background and digital-editing requirements. Aadhaar enrolment uses a live photograph.\n\nSocial media helpers provide templates and general guidance. They do not access your account or guarantee reach, engagement or platform compliance. AI results may be inaccurate; review them before use.",
  },
  advertising: {
    title: "Advertising & funding",
    body: "Updated 8 October 2026\n\nToolinger is free to use. It is prepared to support clearly labelled Google AdSense display advertising after the publisher account, inventory and consent platform are configured. Advertising is currently disabled. Tool features remain available regardless of your advertising choice.\n\nEditorial independence\nAds do not determine tool calculations or recommendations. Sponsored placements must be labelled. Toolinger does not sell tool inputs, identity photos, planner entries or exported files to advertisers. Ads must not imitate download buttons or obscure tool controls.\n\nChoices and third parties\nGoogle and advertising partners may process request and device data under their policies. You can refuse optional ad storage, withdraw permission in Advertising privacy choices, or use browser privacy controls. A certified consent platform is required for the prepared integration and for Google’s applicable regional requirements.\n\nPublisher status\nA policy page alone does not guarantee AdSense approval. Activation also needs an approved publisher ID, real ad-unit IDs, a correct ads.txt entry on the domain root and compliance with Google’s current programme policies. Contact lootchaser2026@gmail.com for advertising questions."
  },
  contact: {
    title: "Contact & support",
    body: "Email: lootchaser2026@gmail.com\n\nFor a bug report, include the tool name, browser/device, steps to reproduce and the expected result. Please do not email identity documents, private images, passwords or other sensitive inputs.",
  },
  accessibility: {
    title: "Accessibility",
    body: "Toolinger supports keyboard navigation, visible focus, screen-reader labels, responsive layouts and reduced-motion preferences. Use Tab to move between controls, Enter to activate buttons, and Escape to close dialogs.\n\nIf you encounter a barrier, contact lootchaser2026@gmail.com with the tool name and your browser or assistive technology. We welcome reports that help improve access.",
  },
};
