import {
  ArrowLeftRight,
  Binary,
  Blend,
  BookOpen,
  Braces,
  Calculator,
  CalendarCheck,
  CalendarDays,
  Captions,
  CaseSensitive,
  Coins,
  Combine,
  ContactRound,
  Contrast,
  CookingPot,
  CopyMinus,
  Crop,
  Droplets,
  Eraser,
  FileCode2,
  FileImage,
  FileMinus2,
  FileSearch,
  FileType2,
  Files,
  Fingerprint,
  Flame,
  FlipHorizontal2,
  Focus,
  Globe,
  Hash,
  Images,
  KeyRound,
  Landmark,
  LetterText,
  Link,
  List,
  ListCollapse,
  ListFilter,
  ListOrdered,
  ListTodo,
  Luggage,
  MessageSquare,
  Minimize2,
  NotebookPen,
  PanelsTopLeft,
  Percent,
  PersonStanding,
  Pipette,
  QrCode,
  Quote,
  Receipt,
  Regex,
  Replace,
  RotateCw,
  Ruler,
  Scaling,
  ShoppingBasket,
  Shuffle,
  Smile,
  Split,
  Stamp,
  Sun,
  Tags,
  Text,
  TextSearch,
  Timer,
  Wallet,
  WholeWord,
  Workflow,
} from "lucide-react";
import type { ToolConfig } from "./catalog";
const icons = {
  "qr-code-generator": QrCode,
  "passport-photo-maker": ContactRound,
  "image-to-pdf": FileImage,
  "image-resizer": Scaling,
  "image-format-converter": Images,
  "image-compressor": Minimize2,
  "grayscale-filter": Contrast,
  "sepia-filter": Contrast,
  "brightness-contrast": Sun,
  "rotate-image": RotateCw,
  "flip-image": FlipHorizontal2,
  "image-base64": Binary,
  "image-cropper": Crop,
  "quote-card-generator": Quote,
  "image-watermark": Stamp,
  "image-metadata": FileSearch,
  "color-picker-image": Pipette,
  "image-blur": Blend,
  "image-sharpen": Focus,
  "collage-maker": PanelsTopLeft,
  "merge-pdf": Combine,
  "split-pdf": Split,
  "compress-pdf": Minimize2,
  "pdf-rotate": RotateCw,
  "delete-pdf-pages": FileMinus2,
  "extract-pdf-pages": Files,
  "rearrange-pdf-pages": ListOrdered,
  "pdf-metadata-viewer": FileSearch,
  "add-page-numbers": ListOrdered,
  "text-to-pdf": FileType2,
  "html-to-pdf": FileType2,
  "pdf-preview": FileSearch,
  "word-counter": WholeWord,
  "character-counter": WholeWord,
  "line-counter": List,
  "case-converter": CaseSensitive,
  "remove-extra-spaces": Eraser,
  "find-replace": Replace,
  "duplicate-line-remover": CopyMinus,
  "text-sorter": ListFilter,
  "text-reverser": ArrowLeftRight,
  "markdown-preview": FileCode2,
  "sentence-counter": WholeWord,
  "reading-time": BookOpen,
  "slug-generator": Link,
  "text-cleaner": Eraser,
  notepad: NotebookPen,
  "text-to-pdf-doc": FileType2,
  "json-formatter-doc": Braces,
  "json-validator-doc": Braces,
  "txt-downloader": NotebookPen,
  "html-formatter-doc": Braces,
  "css-formatter-doc": Braces,
  "js-formatter-doc": Braces,
  "json-formatter": Braces,
  "json-validator": Braces,
  "base64-encoder": Binary,
  "base64-decoder": Binary,
  "url-encoder": Link,
  "url-decoder": Link,
  "html-formatter": Braces,
  "css-formatter": Braces,
  "javascript-formatter": Braces,
  "uuid-generator": Fingerprint,
  "password-generator": KeyRound,
  "hash-generator": Hash,
  "timestamp-converter": CalendarDays,
  "regex-tester": Regex,
  "color-converter": Pipette,
  "bmi-calculator": PersonStanding,
  "bmr-calculator": Flame,
  "calorie-calculator": Flame,
  "water-intake-calculator": Droplets,
  "body-fat-estimator": PersonStanding,
  "emi-calculator": Landmark,
  "simple-interest": Landmark,
  "compound-interest": Landmark,
  "loan-calculator": Landmark,
  "discount-calculator": Percent,
  "gst-calculator": Calculator,
  "profit-margin": Percent,
  "percentage-calculator": CalendarDays,
  "length-converter": Ruler,
  "weight-converter": Ruler,
  "temperature-converter": Ruler,
  "area-converter": Ruler,
  "volume-converter": Ruler,
  "speed-converter": Ruler,
  "storage-converter": CalendarDays,
  "time-converter": Ruler,
  "energy-converter": Ruler,
  "pressure-converter": Ruler,
  "facebook-post-formatter": Braces,
  "facebook-caption-generator": Captions,
  "facebook-hashtag-helper": Hash,
  "facebook-engagement-planner": CalendarDays,
  "facebook-dimension-guide": MessageSquare,
  "instagram-caption-formatter": Braces,
  "instagram-hashtag-organizer": Hash,
  "instagram-bio-counter": Tags,
  "instagram-dimension-helper": Tags,
  "instagram-reel-caption": Tags,
  "youtube-title-counter": LetterText,
  "youtube-description-formatter": Braces,
  "youtube-tag-organizer": Tags,
  "youtube-thumbnail-dimensions": Scaling,
  "youtube-timestamp-generator": CalendarDays,
  "youtube-template-generator": Captions,
  "ai-sentiment": Smile,
  "ai-semantic-similarity": Workflow,
  "ai-extractive-summary": ListCollapse,
  "ai-keyword-extractor": TextSearch,
  "coin-flip": Coins,
  "random-number-generator": Shuffle,
  "random-name-picker": Shuffle,
  "countdown-helper": CalendarDays,
  "age-calculator": CalendarDays,
  "tip-calculator": Receipt,
  "binary-converter": Binary,
  "lorem-generator": Text,
  "daily-planner": ListTodo,
  "habit-tracker": CalendarCheck,
  "expense-tracker": Wallet,
  "shopping-list": ShoppingBasket,
  "focus-timer": Timer,
  "hydration-tracker": Droplets,
  "savings-goal": Landmark,
  "split-bill": Receipt,
  "meal-planner": CookingPot,
  "recipe-scaler": CookingPot,
  "date-calculator": CalendarDays,
  "world-clock": Globe,
  "unit-price-comparison": Ruler,
  "packing-checklist": Luggage,
};
export function ToolIcon({
  tool,
  size = 23,
}: {
  tool: ToolConfig;
  size?: number;
}) {
  const Symbol = icons[tool.id as keyof typeof icons];
  return <Symbol size={size} strokeWidth={1.7} aria-hidden="true" />;
}
